### Create User
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
 "username":"ravi456",
 "email":"ravi456@gmail.com",
 "dateOfBirth":"2000-12-03",
 "mobileNumber":909090
}

###
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
 "username":"vindhya",
 "email":"vindhu@gmail.com",
 "dateOfBirth":"2000-12-03",
 "mobileNumber":909090
}

###

### Read All Users
GET http://localhost:4000/user-api/users

###

### Read User By ID
GET http://localhost:4000/user-api/users/6a05de6bba3007b268a46049

###

### Delete User By ID
DELETE http://localhost:4000/user-api/users/6a05de6bba3007b268a46049

###

### Activate User
PATCH http://localhost:4000/user-api/users/6a05de6bba3007b268a46049